### PR TITLE
created random forest classifier

### LINKED ISSUE #7: Random Forest Classifier
**Creating a Random Forest Classifier**
Fork the dataset and the Python notebook

Locate **#Issue 7** in the Jupyter notebook (or just add it in the end after the solution to issue #6 )
This issue requires you to make 2 Random Forest Classifier models
RF1:
In a new cell, define a new Random Forest Classifier. Use default parameters (Model does not have to be created from scratch, sci-kit learn defined models are accepted).
Use the variable 'rf1' to instantiate this model, and fit it on the training data. Make predictions on the test data.

RF2:
In a new cell, define another Random Forest Classifier. In this one, you are expected to fine tune the parameters of the model and obtain the best accuracy you can achieve. The bounty for this issue is variable and will be given on the performance of this second RF model. Naturally, we expect it to perform better than the KNN model (Model doesn't have to be defined from scratch, sci-kit learn defined models are accepted). 
Train it on the training data and predict on the test data.

(Note: Don't perform scaling/train test split again, work only with tuning the model parameters)

Your PR must contain the edited ipynb file with the same name as the original. 
You must also briefly explain in your words what parameters you changed and their effect (in short). This can be inserted within the file using markdown or docstring.

Kindly edit only the block of code pertaining to the issue :)

### PR DESCRIPTION
**Pull request by abhishek-mishra17**
created a random forest classifier with an accuracy of 71% after hyper tuning

close #7

### CODE REVIEW

**Comment by pk-95** [comment]
Hey man could you gimme a small brief of why you changed these parameters and how they affect the model :)

**Comment by abhishek-mishra17** [comment]
Brief about the rcc parameters:
So basically random forest is an ensemble model (i.e simply a collection of decision trees) , the parameters I changed here are :

**1. n_estimators :** This is basically the number of individual trees present in the forest. Now each tree gives its own prediction and 
                           then the majority of the each individual prediction is considered as the final prediction.
                           so I changed this because the more  number of trees you have (usually) , there could be a better chance of 
                           getting an accurate prediction.

**2. max_depth:**     It is basically the hieght of the tree, so changing this does affect the accuracy of the model , so it is important to find an optimal value for this (not very low and not very high). Increasing the max_depth does incraese the perfomance of the model initially but then it slowly starts to decrease.

**Comment by pk-95** [comment]
Alright awesome!

**Comment by pk-95** [comment]
!bounty 100

**Comment by pk-95** [comment]
Also just wondering, did you tune random state as well? xD Just wanted to know for myself, separate from the cometition

**Comment by abhishek-mishra17** [comment]
I actually just chose 42 as random state, but then when I tried with different random states luckily 42 gave the best results 😃

**Comment by pk-95** [comment]
Ahaha alright good to know xD Yeah 42 is one of the common states chosen I've heard, idk why that's a 'convention' almost 
😂
As for the random state tuning, just for future reference, I guess most people are of the opinion that it shouldn't be done as it shows a more optimistic result rather than a realistic one. Although I'm sure you know all this, you seem to be quite thorough w your work xD

**Pull request merged**
