### PR TITLE
created a heatmap for correlation

### LINKED ISSUE #1: Plot a correlation heatmap
**Plot a correlation heatmap**
Fork the dataset and the Python notebook

Locate **#Issue 1** in the Jupyter notebook
Using ALL columns in the data set, plot a correlation heatmap.
Print the names of the 4 features that have the highest correlation with Quality

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

### PR DESCRIPTION
**Pull request by abhishek-mishra17**
created a heatmap for correlation using seaborn

Closes #1

### CODE REVIEW

**Comment by abhishek-mishra17** [comment]
@pk-95  please review this.
I have closed issue #1

**Comment by pk-95** [comment]
Hey @abhishek-pes , would just suggest one change, could you have the % correlation shown in the heatmap as well? Looks lovely apart from that :)

**Comment by pk-95** [comment]
!bounty 15

**Comment by abhishek-mishra17** [comment]
Thanks a lot

**Pull request closed without merging**
