### PR TITLE
Closing Issue#8-Better Models

### PR DESCRIPTION
**Pull request by RakshithRAcharya**
Closing Issue #8 
Tried predicting wine quality with Logistic Regression, KNN, Random Forest, Support Vector Machines(SVM), Gradient Boosting with parameter tuning to obtain higher accuracy
1) Logistic Regression - 87.5%(without tuning)
                                 - 88.25%(with parameter tuning)
2)KNN - 86.25%(without tuning)
           - 89%(with parameter tuning)
3)RF - 90.5%
       - 90.75%
4)SVM - 85.75%
           - 91.75%
5)Gradient Boosting - 87.5%
                              - 88.75%

### CODE REVIEW

**Comment by RakshithRAcharya** [comment]
This also solves Issue #7 and Issue #6

**Comment by pk-95** [comment]
Hey @RakshithRAcharya , thanks for your contribution. Gimme a while, will go through it :)

**Comment by pk-95** [comment]
Hey @RakshithRAcharya , this notebook is super great :) You've done a great job. Would just like to point out though, this ipynb wouldn't cover issue #6  and #7 as those require you to use the 4 given feature columns as is, and work only with model parameters. You can attempt 6 and 7 w separate PR's with these conditions if you wish :)

**Comment by pk-95** [comment]
But yeas loved the notebook, you will be getting 50 brownie points as well!

**Comment by pk-95** [comment]
!bounty 400

**Comment by RakshithRAcharya** [comment]
Thank You @pk-95

**Comment by techverve** [comment]
!bounty 300

**Pull request closed without merging**
