### PR TITLE
created scatter plot

### LINKED ISSUE #3: Plotting Scatter-plots
**Scatter Plots**
Fork  and clone the dataset and the Python notebook

Locate **#Issue 3** in the Jupyter notebook
Scatter plots need to be plotted amongst each of the feature columns ( taking all possible combinations of 2) and must be given the 'hue' of the target columns, 'quality'. Mention trends, if any, using print statements. 

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

### PR DESCRIPTION
**Pull request by abhishek-mishra17**
created scatter plot for all possible combination (in 2's) and drew inferences from the most prominent one.

Closes #3

### CODE REVIEW

**Comment by pk-95** [comment]
!bounty 20

**Comment by pk-95** [comment]
!bounty 30

**Comment by pk-95** [comment]
corrected 20 to 30 :)

**Comment by abhishek-mishra17** [comment]
Thanks a lot

**Pull request closed without merging**
